# -*- coding: utf-8 -*-
"""
Four Elements — visual screenshots sync helper.
Copies local Playwright screenshots into Google Drive mirror.

Source:
  _reports/screenshots/latest/*.png

Destination:
  <FourElements_WORK_MIRROR>/visual_screenshots/latest/*.png

This helper is intentionally independent from gameplay code.
"""
from __future__ import annotations

import os
import shutil
from datetime import datetime
from pathlib import Path

MIRROR_FOLDER_NAME = "FourElements_WORK_MIRROR"


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def candidate_mirror_paths(root: Path) -> list[Path]:
    paths: list[Path] = []

    env_value = os.environ.get("FE_WORK_MIRROR") or os.environ.get("FOUR_ELEMENTS_WORK_MIRROR")
    if env_value:
        paths.append(Path(env_value))

    # Real path used in current setup, visible in sync output.
    paths.append(Path(r"G:\Мой диск") / MIRROR_FOLDER_NAME)
    paths.append(Path(r"G:\My Drive") / MIRROR_FOLDER_NAME)
    paths.append(Path(r"G:") / "Мой диск" / MIRROR_FOLDER_NAME)
    paths.append(Path(r"G:") / "My Drive" / MIRROR_FOLDER_NAME)

    user_home = Path.home()
    paths.append(user_home / "Google Drive" / "Мой диск" / MIRROR_FOLDER_NAME)
    paths.append(user_home / "Google Drive" / "My Drive" / MIRROR_FOLDER_NAME)
    paths.append(user_home / "My Drive" / MIRROR_FOLDER_NAME)

    # Optional local marker generated by prior sync tools.
    for marker in [root / "_gpt_state" / "LAST_SYNC.txt", root / "_gpt_state" / "README_MIRROR_PLAN.txt"]:
        if marker.exists():
            try:
                text = marker.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                continue
            for line in text.splitlines():
                if "FourElements_WORK_MIRROR" in line:
                    value = line.split("=", 1)[-1].strip().strip('"')
                    if value:
                        paths.append(Path(value))

    unique: list[Path] = []
    seen: set[str] = set()
    for path in paths:
        key = str(path).lower()
        if key not in seen:
            unique.append(path)
            seen.add(key)
    return unique


def find_mirror(root: Path) -> Path | None:
    for path in candidate_mirror_paths(root):
        if path.exists() and path.is_dir():
            return path
    return None


def main() -> int:
    root = project_root()
    source_dir = root / "_reports" / "screenshots" / "latest"

    if not source_dir.exists():
        print(f"[WARN] No visual screenshots source folder: {source_dir}")
        return 0

    pngs = sorted(source_dir.glob("*.png"))
    if not pngs:
        print(f"[WARN] No PNG screenshots found in: {source_dir}")
        return 0

    mirror = find_mirror(root)
    if not mirror:
        print("[WARN] Google Drive mirror path not found; visual screenshots not synced.")
        print("[INFO] Set FE_WORK_MIRROR to the full mirror path if needed.")
        return 0

    target_root = mirror / "visual_screenshots"
    target_latest = target_root / "latest"

    if target_latest.exists():
        shutil.rmtree(target_latest)
    target_latest.mkdir(parents=True, exist_ok=True)

    copied = 0
    for src in pngs:
        shutil.copy2(src, target_latest / src.name)
        copied += 1

    manifest = target_root / "VISUAL_SCREENSHOTS_MANIFEST.txt"
    lines = [
        "Four Elements — visual screenshots mirror",
        f"generated_at={datetime.now().isoformat(timespec='seconds')}",
        f"source={source_dir}",
        f"mirror={mirror}",
        f"target={target_latest}",
        f"visual_screenshot_files={copied}",
        "",
        "files:",
    ]
    for src in pngs:
        dst = target_latest / src.name
        lines.append(f"- {src.name} ({dst.stat().st_size} bytes)")
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[OK] visual_screenshot_files: {copied}")
    print(f"[OK] visual_screenshots_target: {target_latest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
